### ISSUE TITLE
Multipackage repo for all bitshares JS?

### ISSUE THREAD

**Issue by skyl** [bitshares/bitsharesjs#12]
The JavaScript packages in the bitshares org https://github.com/bitshares might be better organized, easier to understand, more cohesive and easier to publish as a monorepo using tools like yarn workspaces and lerna. Is there a document that explains how bitshares-ui, bitsharesjs, bitsharesjs-ws, bitshares-js, bitshares-ui-api, perfect-scrollbar, reconnecting-websocket, etc are related to eachother. As a newbie, I'm having a hard time understanding what is what.

I'm looking to get a little bit of data from the blockchain. I think this (bitshares/bitsharesjs) is the package I care about at the moment. But, I look at all the nice modules in bitshares-ui https://github.com/bitshares/bitshares-ui/tree/staging/app/components and can't help but think that some might be able to be released to npm as separate modules... The only way this would be practical is if a tool like lerna is used to publish.

**Comment by sschiessl-bcp** [comment]
bitsharesjs is the high level library that provides access to the chain via stores, caching and automated subscription. bitsharesjs-ws provides the low level modules for the connection to the blockchain via websockets. The other repository are frontends and helper/forks for the UI
