### ISSUE TITLE
Terminating a ws connection takes forever, why?

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitsharesjs#24]
I am testing new reconnection strategy for UI and I found that it takes forever when ChainWebSocket recognizes that connection is dead until the rpc_connection_status in BlockchainStore is updated.

Why is that @svk31 ? You can test it by simply opening the UI and disabling the internet connection after connection has been established. Are there any timeouts involved that are possibly to high?

![image](https://user-images.githubusercontent.com/33128181/42309257-5a959cb2-8038-11e8-80ec-13166a598679.png)

**Comment by svk31** [comment]
Not sure, but the issue belongs in bitsharesjs-ws or bitshares-ui
