### ISSUE TITLE
Add a link in readme to hackthedex.io

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitsharesjs#33]
As a community member I want a link to https://hackthedex.io (the bounty program) in the main page of this repository, so that people who find a security issue will know where and how to report it.

**Comment by manikey123** [comment]
claiming this

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitsharesjs/commit/441cd10abe0a554832197465cdcfd68b1597c017
