### ISSUE TITLE
Market subscription

### ISSUE THREAD

**Issue by ronenteva** [bitshares/bitsharesjs#4]
Where can I read about how to `subscribe_to_market` using this package?

**Comment by svk31** [comment]
You would not do that using this package; this package is for constructing and serializing transactions, `subscribe_to_market` is an api call that you can use with bitsharesjs-ws.

Definition in bitshares-core:
https://github.com/bitshares/bitshares-core/blob/master/libraries/app/database_api.cpp#L1080

Use in bitshares-ui:
https://github.com/bitshares/bitshares-ui/blob/master/app/actions/MarketsActions.js#L232
