### ISSUE TITLE
Wrong prefix during transaction validation.

### ISSUE THREAD

**Issue by vladikus10** [bitshares/bitsharesjs#40]
When I try to create an `account_update` transaction using a bitShares public key (example: `BTS7yXA4684QDr9Rhz8JfTQEwcu8n8DJE4Z9WJ42GjpufCMVpfs6h`), I get this error:

```
account_update.owner	 cause: authority.key_auths	 cause: Expecting key to begin with GPH, instead got B
```
How do I change the prefix check to `BTS` instead?

**Comment by vladikus10** [comment]
Digging through the source code, I did notice that the `address_prefix` comes from the `bitsharesjs-ws` module `ChainConfig`, I tried changing the prefix:
```
import { ChainConfig } from 'bitsharesjs/node_modules/bitsharesjs-ws';
 ChainConfig.setPrefix('BTS');
```
But it did not help.

**Comment by sschiessl-bcp** [comment]
You need to do something like this 

```
export function getBlockchainConfig() {
    return {
        name: "SOMENAME",
        address_prefix: "SOMEPREFIX",
        chain_id:
            "someid",
        core_asset: "SOMECORE"
    };
}
const blockchainConfig = getBlockchainConfig();
ChainConfig.networks[blockchainConfig.name] = blockchainConfig;
```
