### ISSUE TITLE
AES Encrypt

### ISSUE THREAD

**Issue by SYLing** [bitshares/bitsharesjs#41]
aes.encryptToHex(encryption_buffer)
AES encryption results are 96 bits。
How to do at iOS or Objective-C?

**Comment by SYLing** [comment]
AES CBC pkcs5padding 
key: fa585d89c851dd338a70dcf535aa2a92fee7836dd6aff1226583e88e0996293f
iv : 16bc009c652826e0fc5c706695a03cdd
Data : 5Jvvtu48QUxgXCJRoKBZoqwb4yVJKyotDoxzpR4N1Ln2StWXDvQ

result :0bafc2d01c0bf418d4850925de0b7a133dbc67aa1ba7684bc4acb4e7760e1b21d6b6769cd1093e9d66c180c45aa608512c317e700963ce2c9c410e2ab4d0bd0f



bitsharesjs result : 1f0cec2e7e3f2e937c222fb8b0f6e192c0d7244320ae2c10195997889aca38585493a586d461fa1ff87232a44463f627750546c69570e33bce17f04da7917b0a


They is different。

**Comment by sschiessl-bcp** [comment]
Please have a look how it is done here
https://github.com/bitshares/bitsharesjs/blob/3f191d75134e6203cb29f748f3a2e62b03414f1f/lib/ecc/src/aes.js#L215
