### ISSUE TITLE
[1][dot5enko] Add support for market fee sharing

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitsharesjs#45]
`extensions` field of `asset_options` has a new type in bitshares-core 3.0.0: https://github.com/bitshares/bitshares-core/blob/3.0.0/libraries/chain/include/graphene/chain/protocol/asset_ops.hpp#L85, we need to
- [ ] update serialization of `asset_create_operation` and `asset_update_operation`

**Comment by sschiessl-bcp** [comment]
Do we have a taker? @dot5enko :)

**Comment by dot5enko** [comment]
@sschiessl-bcp. took. ETA: todays evening

**Comment by dot5enko** [comment]
@sschiessl-bcp i've added serialization by hand. as current js_serializator from core unable to do this. i've tried different PR's with serialization improvements but no result as well. probably i'll look at it on a weekend )

**Comment by sschiessl-bcp** [comment]
Please reach out here https://github.com/bitshares/bitshares-core/issues/1701, possible you can together fix the serializer formatting
