### ISSUE TITLE
generateKeys() returns public keys with incorrect prefix if same account-password combination was already processed with it using another prefix

### ISSUE THREAD

**Issue by femtocat** [bitshares/bitsharesjs#46]
> const bts = require('bitsharesjs');
undefined
> bts.Login.generateKeys("randomaccount-777", "thisisafakepassword", ['active', 'owner', 'memo'], 'FAKEPREFIX').pubKeys
{ active: 'FAKEPREFIX6jhmykDHAfUyCLVBkjzYN2jdhdcNtXv3BrBr1u3byz2wphSBNh',
  owner: 'FAKEPREFIX6xKHNcqgJnEdMETPcxxAaPZwfjiqgXPn7NHsCGMxTqcqb3HwNd',
  memo: 'FAKEPREFIX5uUuJNu7i1F6Q9ZrFAhuVPnG5f8UcMoTdtjy3CRJxRQszkNA4U' }
> bts.Login.generateKeys("randomaccount-777", "thisisafakepassword", ['active', 'owner', 'memo'], 'BTS').pubKeys
{ active: 'FAKEPREFIX6jhmykDHAfUyCLVBkjzYN2jdhdcNtXv3BrBr1u3byz2wphSBNh',
  owner: 'FAKEPREFIX6xKHNcqgJnEdMETPcxxAaPZwfjiqgXPn7NHsCGMxTqcqb3HwNd',
  memo: 'FAKEPREFIX5uUuJNu7i1F6Q9ZrFAhuVPnG5f8UcMoTdtjy3CRJxRQszkNA4U' }

**Comment by sschiessl-bcp** [comment]
ChainConfig must know the chain you are trying to get keys for (see bitsharesjs-ws ChainConfig)
