### ISSUE TITLE
ESDOC geneterate fails:

### ISSUE THREAD

**Issue by Tadasu85** [bitshares/bitsharesjs#5]
Firstly esdoc-title isnt needed causes compile to fail.

Second compile fails with stack heap:::

==== JS stack trace =========================================

Security context: 0x295cf68cfb39 <JS Object>
    1: DoJoin(aka DoJoin) [native array.js:~129] [pc=0x2b374224ccbd] (this=0x295cf6804381 <undefined>,w=0xb50f3498c89 <JS Array[7]>,x=7,N=0x295cf68043c1 <true>,J=0xb50f347b8d1 <String[4]\: ,\n  >,I=0x295cf68b46c9 <JS Function ConvertToString (SharedFunctionInfo 0x295cf6852dc9)>)
    2: Join(aka Join) [native array.js:180] [pc=0x2b3741b18032] (this=0x295cf6804381 <undefined>,w=0xb50f3498c89 <JS ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x109b7ac [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Runtime_StringBuilderJoin(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x2b3741a092a7
Aborted (core dumped)

**Comment by svk31** [comment]
Fixed here: https://github.com/bitshares/bitsharesjs/commit/f19edcfd175943b9c9de31baaf2f367b988bfa13
