### ISSUE TITLE
Streamline for core 3.2.0

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitsharesjs#54]
https://github.com/bitshares/bitshares-core/issues/1808#issuecomment-504472108

Task:
 - [ ] Go through all API changes and work out if any serialization adjustments are necessary

**Comment by sschiessl-bcp** [comment]
@dot5enko ?

**Comment by dot5enko** [comment]
@sschiessl-bcp yup, i'll take over this

**Comment by dot5enko** [comment]
@sschiessl-bcp this one https://github.com/bitshares/bitshares-core/issues/1734, you've checked it?

**Comment by dot5enko** [comment]
no serialization adjustments required

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp this one [bitshares/bitshares-core#1734](https://github.com/bitshares/bitshares-core/issues/1734), you've checked it?

No haven't, should have an open issue.

**Comment by sschiessl-bcp** [comment]
@dot5enko your hours?

**Comment by dot5enko** [comment]
@sschiessl-bcp 1 hour
