### ISSUE TITLE
How to import this library in an Angular App?

### ISSUE THREAD

**Issue by senthil-kumar-r** [bitshares/bitsharesjs#60]
1. I install the BitsharesJS and BitsharesJS-WS in my angular app
2. Include bitsharesjs.js and bitshresjs-ws.js in angular.json of the app under "scripts"
3. Include a custom JS file custom-ws.js in asset and include the same in angular.json
4. In my custom-ws.js I am able to connect testnet server and can write methods to use db_api, history_api
5. BUT I am not able to import bitsharesjs, to use account_create class for creating new user account.

Please help me to use classes in bitsharesjs in the custom js file / directly use the class in Angular component,

**Comment by sschiessl-bcp** [comment]
Are you using `npm` for your app?

**Comment by senthil-kumar-r** [comment]
@sschiessl-bcp Yes, using  `npm` I installed both libraries.

**Comment by sschiessl-bcp** [comment]
Import them like any other library, no need to manually add it to scripts.

**Comment by senthil-kumar-r** [comment]
@sschiessl-bcp how to use `https://bitsharesjs.bitshares.org/variable/index.html#static-variable-account_create`
i.e) from the app I want to create an account for registered user.

**Comment by sschiessl-bcp** [comment]
Have a look at https://github.com/bitshares/bitshares-ui, there should be examples for everything.

**Comment by senthil-kumar-r** [comment]
Now I import classes directly in my component ts file. Let say I can `import Apis from bitsharesjs-ws` and use `var {ops} = require("bitsharesjs");` in ts file.
While do `console.log(ops);` I getting objects (refer screenshot). but still I do not know how to use this object / execute method to create an account in testnet

![ops_account_create](https://user-images.githubusercontent.com/10301870/72890099-2ca92680-3d37-11ea-9821-4c062ec4884f.png)

**Comment by sschiessl-bcp** [comment]
Please have a look at the above link to see how it uses the API, might need to dig through the library.

**Comment by senthil-kumar-r** [comment]
@sschiessl-bcp as per your suggestion, I refer the library and able to send request to my testnet for `account_create` but I am getting response as blank, please refer below screenshot
![Screenshot 2020-01-23 at 9 45 19 PM](https://user-images.githubusercontent.com/10301870/73002343-e54f9280-3e29-11ea-91d2-736e3693a66a.png)
The code is


[account_create.txt](https://github.com/bitshares/bitsharesjs/files/4104082/account_create.txt)

**Comment by senthil-kumar-r** [comment]
@sschiessl-bcp I have a register form in my mobile app, once an user register in the app then I have to create an account in Bitshare, using BitsharesJS.
I think I have to use this library - https://bitsharesjs.bitshares.org/variable/index.html#static-variable-account_create but I do not know how to use it.
By referring this example: https://github.com/bitshares/bitsharesjs/blob/master/examples/createHtlc.js#L27 I tried
```
const new_user_info = {
   registrar: "1.2.680",
   referrer: "1.2.680",
   name: "demo-user",
   owner: {
          weight_threshold: "dsfdsfdsf32434324",
          account_auths: "8987987DFDSCXVX",
          key_auths: "3546356HJDSFDSF",
          address_auths: "343432dsfSDFDSF"
    },
    active: {
          weight_threshold: "dsfdsfdsf32434324",
          account_auths: "8987987DFDSCXVX",
          key_auths: "3546356HJDSFDSF",
          address_auths: "343432dsfSDFDSF"
    },
   extensions: {
    target_collateral_ratio: 250
   }
}
let tr = new TransactionBuilder();
tr.add_type_operation("account_create", faucet_user_info).then(res => {
        console.log('res', res)
});
```
but it returns an error Error:
`Error: account_create.owner	 cause: authority.account_auths	 cause: Expecting account in format 1.2.[0-9]+ instead of D stack: Error: Expecting account in format 1.2.[0-9]+ instead of D  D`

**Comment by senthil-kumar-r** [comment]
@sschiessl-bcp is it not possible to create an account by simple with fields like name, owner_key, active_key and memo_key?
do we need all params like - active.weight_threshold, owner.account_auths, etc?

**Comment by sschiessl-bcp** [comment]
Please have a look how the UI does it through `AccountActions.createAccountWithPassword`. Try to read up in the docs how an account is setup. The fields are necessary because accounts are linked through weighted permissions to public keys in BitShares

**Comment by senthil-kumar-r** [comment]
@sschiessl-bcp Ok. I do have private server  i.e `<my-private>.<mydomain>.com`
from my localhost I can connect the Server through `API.instance` and able to get Keys using `Login`.
The code is

> `import { Apis } from 'bitsharesjs-ws';`
> `var { Login, ChainStore } = require("bitsharesjs");`
> `let server = "ws://<myprivate>.<mydomain>:8090/"`
> `Apis.instance(server, true).init_promise.then((res) => {`
> `let generatedKeys = Login.generateKeys(<newAccountName>, <newAccountPassword>, ['active', 'owner','memo'], 'TEST');`
>` });`
BUT from my development server I can not connect to the Private Server.
I tried the server url with `wss://` and also with port `8091` and I am getting below error.
![error](https://user-images.githubusercontent.com/10301870/73590782-75699800-450c-11ea-9d9d-ece87ed68069.jpg)

**Comment by senthil-kumar-r** [comment]
@sschiessl-bcp can you please guide to do Login check of Bitshares users in my app?
That is I created an account through faucet and then want the user to login to do Transfer in my app, I checked in https://bitsharesjs.bitshares.org/file/lib/chain/src/AccountLogin.js.html it has option to generate Keys and to check the Keys and it is not for validating username and password.

I find a way here https://bitsharesjs.bitshares.org/file/lib/chain/src/ChainStore.js.html#lineNumber677 to validate the username but NOT the password.

Please help.

**Comment by senthil-kumar-r** [comment]
@sschiessl-bcp when I use my private testnet it is getting `duplicate transaction` throws transaction id {$txn_id} is already stored in database.
No clue about this issue, please help.
I attached the code.
[transfer.js.txt](https://github.com/bitshares/bitsharesjs/files/4256187/transfer.js.txt)

**Comment by sschiessl-bcp** [comment]
```
		auths: {
			memo: [[generatedKeys.pubKeys.active]],
			owner: [[generatedKeys.pubKeys.owner]],
			active: [[generatedKeys.pubKeys.memo]]
		}
```

There is a mixup of keys in your code here.
