### ISSUE TITLE
Transfer with memo sample code is using wrong memo key

### ISSUE THREAD

**Issue by RuneStone0** [bitshares/bitsharesjs#62]
The current [transfer code example](https://github.com/RuneStone0/bitsharesjs/blob/95aa8bfabbd8eab1562c4b322228bb01ba056866/examples/transfer.js) is not working when using memo. The sample code is using the active private key to encrypt the memo instead of the private memo key.

**Comment by sschiessl-bcp** [comment]
Thanks!
