### ISSUE TITLE
To select WSS node with lowest latency

### ISSUE THREAD

**Issue by senthil-wd** [bitshares/bitsharesjs#66]
I am using BitsharesJS WS library to connect the Bitshare server. I wanted to use one or multi node server to connect Bitshare server with low latency. 
I am not sure how to get available public WS nodes? and how to find the low latency among the public WS nodes?
Please suggest.

**Comment by sschiessl-bcp** [comment]
This is how ref UI does it https://github.com/bitshares/bitshares-ui/blob/02c95d6607ed34a81287cfe9e6c05fdf28d1d4e5/app/routerTransition.js#L807

**Comment by abitmore** [comment]
@senthil-wd please find public nodes here: https://github.com/bitshares/bitshares-ui/blob/develop/app/api/apiConfig.js .
