### ISSUE TITLE
public/un-encrypted memo

### ISSUE THREAD

**Issue by baabeetaa** [bitshares/bitsharesjs#8]
```
If @ref from == @ref to and @ref from == 0 then no encryption is used, the memo is public.
```
https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/protocol/memo.hpp#L36

However, Im not able to set these params to null or undefined (void 0).
https://github.com/bitshares/bitsharesjs/blob/master/lib/serializer/src/operations.js#L393

BTW, I can still set the ```message``` to clear text as a workaround.

Is is a bug or I am missing anything?
Thank you,

**Comment by xeroc** [comment]
On chain, the from and to fields are not optional, but required. A work around would be to use the 'all-zero pubkey' (properly formated with checksum etc). That could be used to indicate plaintext
