### ISSUE TITLE
ChainValidation.is_valid_symbol_error("A.ABC")) returns null

### ISSUE THREAD

**Issue by freak5g** [bitshares/bitsharesjs#80]
Should throw error or I'm wrong?
https://github.com/bitshares/bitsharesjs/blob/db009153e4f0bfaf04e43db393b3aa45f6de72ab/lib/chain/src/ChainValidation.js#L115

**Comment by abitmore** [comment]
I think it should throw. But perhaps it does not matter, because you need to own `A` to be able to create `A.ABC`, but `A` is not valid.

**Comment by freak5g** [comment]
Yes, you're right, it doesn't matter. It is for one particular use case only.
